### ISSUE TITLE
Rigidbodies: time dependent properties / and / rigid body outputs

### ISSUE THREAD

**Issue by Ehsanizadi** [GPUSPH/gpusph#10]
Hi,
I've simulated a falling cylinder hitting a mud layer. the cylinder will penetrate intor the mud layer. I have two questions:

* As you see [here] (https://www.youtube.com/watch?v=WWNho4FAXaE) the mud layer still fluctuating when the cylinder is hitting it.  I needed the mud layer to be settle and reaches an almost stable situation when the cylinder hits it. So, I tried to make some delay in the time of application of gravity. I used gcallback, but I did not change the gravity of the fluid (since it should be there until the movements of the mud to be damped). In the gcallback class I used suchg code:
```
float3 Trial::g_callback(const float t)
{
	if(t<15){
                ODEGravity=make_float3(0.0, 0.0, 0.0);
		dWorldSetGravity(m_ODEWorld, ODEGravity.x, ODEGravity.y, ODEGravity.z);
		m_physparams.gravity=make_float3(0.,0.,-9.81f);
	}
	else{
		ODEGravity=make_float3(0.0, 0.0, -9.81);
		dWorldSetGravity(m_ODEWorld, ODEGravity.x, ODEGravity.y, ODEGravity.z);
		m_physparams.gravity=make_float3(0.,0.,-9.81f);
	}
	return m_physparams.gravity;
}
```
it worked. My question is that can I change whatever paramater as I wish within the time, like this method?
I was thinking that perhaps a having a function would be appreciated for changing the properties of rigid bodies, or even the fluid itself with regard to time.  For example changing viscosity with time. 

* For the case I described above, how can I get the accelration/velocity/ and position of the rigid body (cylinder)? I don't think I can get them using "TESTPOINTSPART" sinc ethe rigid body is not in a fixed position always.

**Comment by Ehsanizadi** [comment]
By studying some simple examples of ODE I found the answer to the second questions.
At the end of g_callback class, I added this:
```
if (t>15.5 && t<16) {
		outputData << t << " " << dBodyGetForce(cylinder.m_ODEBody)[2] << " " << dBodyGetLinearVel(cylinder.m_ODEBody)[2] << endl;
}
```
It writes time, force and its velocity in z direction.

**Comment by Narcolessico** [comment]
Hello,

I would not recommend changing simulation parameters in the gravity callback: it is only designed to return a float3 and changing the simulator parameters might break the consistency of the simulation (e.g. the engine assumes ODE gravity is the same as GPUSPH gravity). Actually, class encapsulation itself should not allow it.

This being said, it is a smart workaround that anticipates the callback for imposing forces, which is already implemented and will be released soon ([sign up](http://www.gpusph.org/contact/) to stay up to date ;) ). In case you need to access the force from another part of the code (e.g. making your own Writer class and adding it with given frequency), you can find the resulting force acting on a body in `GlobalData::s_hRbTotalForce[device_index][object_index]`.

**Comment by Ehsanizadi** [comment]
Thanks Narcolessico for your comment.
When I use ` GlobalData::s_hRbTotalForce[device_index][object_index]` I always get zero in all three directions.
I guess I fill device and object indices incorrectly. Could you help me how to fill them in?
Sorry for asking this, I am a freshman here!

**Comment by Narcolessico** [comment]
Please note that `s_hRbTotalForce` only contains the force applied to the body by the fluid, so it should be 0 until the body hits the fluid.

You are correct about the indices of the array.

For any question about the simulator and the API, you're welcome to join #gpusph channel on Freenode.

**Comment by Ehsanizadi** [comment]
Thanks.
I did so.
