### ISSUE TITLE
Whats the current status of GPUSPH?

### ISSUE THREAD

**Issue by Ehsanizadi** [GPUSPH/gpusph#14]
Hi,

Its been a long time that there is no news/commits on this repository?
Is it still under development? What features are added? and when the new version is going to be released?

Ehsan

**Comment by alexisherault** [comment]
Hi Ehsan,
there is a long tile we din't commit on the public master branch but we are actively working on the development branches.
A new website and V4.0 will be out for Spheric 2016 next week followed by the end year by a new release with structural improvements.

Alexis.
