### ISSUE TITLE
where is gpusph V4.0?

### ISSUE THREAD

**Issue by RichardGFrench** [GPUSPH/gpusph#15]
The online documentation http://www.gpusph.org/documentation/install-guide/ from July 2016 indicates that there is a version 4.0 on github:

git clone https :// github . com / GPUSPH / gpusph . git
cd gpusph
git checkout v4.0
to get version 4.0 specifically. Otherwise, download the .zipped archive from http:
//github.com/GPUSPH/gpusph/archive/v4.0.zip, and then
unzip v4.0. zip
cd gpusph -4.0
(you may remove v4.0.zip afterwards).

But these instructions don't work and v4.0 is not visible on github.

I am unable to compile v3.0 on OS X because of the following compile error:

make: *** No rule to make target `ode/ode.h', needed by `build/Cone.o'.  Stop.

Thanks for any help.

**Comment by spacegirl1923** [comment]
RichardGFrench,

I had the same issue.  However I found that you need the ODE library http://www.ode.org/  I installed it similarly to CHRONO and I don't think I had to do anything too fancy to get it to compile.

Hope that helps!  

Also v4.0!!!  Can we at least have access to the old documentation for v3.0 so I can do stuff with the old code until you make the 4.0 branch available?

Thanks!

Megan

**Comment by Narcolessico** [comment]
[GPUSPH 4.0](http://www.gpusph.org/gpusph/release/2016/10/19/gpusph-v4/) is out. Sorry for the delay!
