### ISSUE TITLE
Problem DamBreak3D does not run with GPUSPH 4.0

### ISSUE THREAD

**Issue by MatzMatz** [GPUSPH/gpusph#20]
Hello everyone,

I try to run DamBreak3D which successfully compiles on my Ubuntu machine. Execution leads to termination of the program with the following error message:

"Trying to set inertia on a plane!"

This function is called during fill_parts() of class XProblem which leads to the execution of SetInertia in class Plane which has not been implemented (yet).

I don't know if there is some mistake on my side. Anyway, the other problems such as DamBreakGate work just fine. Any comment is highly appreciated! :)

Cheers
Mathias

![errormsg](https://cloud.githubusercontent.com/assets/24430607/20963133/69c1ee84-bc6c-11e6-94cb-770a70901d8d.png)

**Comment by agnesLeroy** [comment]
Hi Mathias,
If you run:
./GPUSPH --use_planes false 
the simulation should run fine.

Cheers,
Agnès

**Comment by MatzMatz** [comment]
Hi Agnès,

thanks for your quick response!
If I disable planes I get another terminate:
Cube::BodyCreate Trying to create a body in an invalid physical system

Cheers
Mathias

![error_dambreak3d_gpusph40_cube](https://cloud.githubusercontent.com/assets/24430607/20969739/a53b2b88-bc8a-11e6-8679-d370f2822ea4.png)

**Comment by agnesLeroy** [comment]
Are you compiling with the option chrono=1 ?

**Comment by MatzMatz** [comment]
Yes I do. Chrono is enabled.

**Comment by MatzMatz** [comment]
Agnes,

without chrono it runs just fine, regardless of the plane setting :D Thanks a lot!!

You think I have a problem with the chrono library?? I thought rigid bodies are not activated in the DamBreak3D example. Why does it affect it then?

**Comment by agnesLeroy** [comment]
DamBreak3D uses features that are not compatible with chrono, this is why you got that problem. We need to investigate this.

Cheers,
Agnès

**Comment by MatzMatz** [comment]
OK I see. Thanks for helping!

Cheers
Mathias

**Comment by Narcolessico** [comment]
Hello, there is already a fix for this, but it's still in the development branch. We'll push the fixes to the master branch ASAP.

Regards,
Eugenio

**Comment by Oblomov** [comment]
I just merged the potential fixes for this issue to the master branch. @MatzMatz, can you please test again with the current master and chrono enabled and verify that it works?

**Comment by MatzMatz** [comment]
I just downloaded the actual master files from git. The fix was successful. The test case DamBreak3D now works without any problem! :)
Thanks a lot!

Mathias


Von: Oblomov [mailto:notifications@github.com]
Gesendet: Mittwoch, 21. Dezember 2016 15:59
An: GPUSPH/gpusph
Cc: Dietzel Mathias; Mention
Betreff: Re: [GPUSPH/gpusph] Problem DamBreak3D does not run with GPUSPH 4.0 (#20)


I just merged the potential fixes for this issue to the master branch. @MatzMatz<https://github.com/MatzMatz>, can you please test again with the current master and chrono enabled and verify that it works?

**Comment by Oblomov** [comment]
Thanks for reporting back, I'm closing this issue now.
