### ISSUE TITLE
searching for help

### ISSUE THREAD

**Issue by cjin987** [GPUSPH/gpusph#22]
Hi:
I used the GPUSPH to compile a model (called OffshorePile). then I could not compile any other other models. all the other tests linked to that model (OffshorePile). see below. Is there anybody who knows how to solve this problem...Thanks very much.

XXX:~/Downloads/gpusph$ make problems=AccuracyTest
[CU] OffshorePile.o              
Compiled with problem **OffshorePile**
Compiled without fastmath
[LINK] dist/linux/x86_64/GPUSPH  
Success.

Compiled with problem **OffshorePile**
Compiled without fastmath
[LINK] dist/linux/x86_64/GPUSPH  
Success.
XXX:~/Downloads/gpusph$ make problems=Mesh_2

Compiled with problem **OffshorePile**
Compiled without fastmath
[LINK] dist/linux/x86_64/GPUSPH  
Success.

**Comment by alexisherault** [comment]
It's make problem=xxx (without s)

Le 30 avr. 2017 à 05:06, cjin987 <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi:
I used the GPUSPH to compile a model (called OffshorePile). then I could not compile any other other models. all the other tests linked to that model (OffshorePile). see below. Is there anybody who knows how to solve this problem...Thanks very much.

XXX:~/Downloads/gpusph$ make problems=AccuracyTest
[CU] OffshorePile.o
Compiled with problem OffshorePile
Compiled without fastmath
[LINK] dist/linux/x86_64/GPUSPH
Success.

Compiled with problem OffshorePile
Compiled without fastmath
[LINK] dist/linux/x86_64/GPUSPH
Success.
XXX:~/Downloads/gpusph$ make problems=Mesh_2

Compiled with problem OffshorePile
Compiled without fastmath
[LINK] dist/linux/x86_64/GPUSPH
Success.

**Comment by cjin987** [comment]
Thanks very much...
It is really really a stupid question...
