### ISSUE TITLE
Expected Viscosity Model Error

### ISSUE THREAD

**Issue by physicsunited** [GPUSPH/gpusph#24]
Dear All Developers,

I am a researching intern with EDF's GPUSPH group, and throughout my work benchmarking the software I noticed a discrepancy in the viscosity models as a whole (as far as I can tell). 

It appears to be that there is a factor of two multiplied by the viscosity parameter defined by the function "set_kinematic_visc(0, 1.0e-2f);" because the expected output velocity in one of my benchmarked case studies is half the theoretical velocity profile. 

This issue has been tested using the different viscosity models (KINEMATIC & DYNAMIC) available (with SA and DYNBOUNDARY) walls, however, the discrepancy appears to be there regardless of the models used. 

Feel free to contact me either here or via my work email if more details or data is required. 
christopher.nahed@edf.fr

**Comment by physicsunited** [comment]
[viscosity error.pdf](https://github.com/GPUSPH/gpusph/files/1035364/viscosity.error.pdf)

The data required to see this problem at hand is in this pdf. Note the case study was for a simple 2D poiseuille flow between two flat plates.

**Comment by agnesLeroy** [comment]
It appeared that there was a factor of two missing in the problem setup that the user was running, which led to the underestimation of the driving acceleration vector. This explains the discrepancy in the results and the current viscosity formulation in GPUSPH seems correct.
