### ISSUE TITLE
aux/UsingGit.txt is obsolete (and in my opinion useless)

### ISSUE THREAD

**Issue by sanguinariojoe** [GPUSPH/gpusph#29]
Apparently the information in aux/UsingGit.txt refers to an old internal Git repo. Also, in case this kind of documentation is required (which is not in my opinion, there are thousands of publicly available superb Git tutorials), shall be moved to a wiki

**Comment by agnesLeroy** [comment]
Hi,
Hum, actually this refers to our private developer repository. This definitely needs an update though. Thank you for pointing it out.
Agnès

**Comment by Oblomov** [comment]
Hello,

UsingGit has now been removed in favour of a more appropriate `CONTRIBUTING` document at the repository root, which defers to the Pro Git book for instructions on how to use git, and highlights the use of the `next` branch as development reference.
