### ISSUE TITLE
gcc cannot find sph

### ISSUE THREAD

**Issue by leo-cheung** [GPUSPH/gpusph#49]
Checking for library sph
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}
err: /usr/bin/ld: cannot find -lsph
collect2: error: ld returned 1 exit status

**Comment by leo-cheung** [comment]
Can we add the GPUSPH into gcc library?

**Comment by Oblomov** [comment]
I am not sure what you are trying to do, but GPUSPH is not a library. User-defined setups are compiled from within the GPUSPH source directory itself.
