### ISSUE TITLE
How to reference GPUSPH properly for a paper?

### ISSUE THREAD

**Issue by AhmedSalih3d** [GPUSPH/gpusph#58]
It is a pretty basic question, but maybe the authors of the programme has a preferred way to be referenced or some initial paper to reference.

Kind regards

**Comment by Oblomov** [comment]
Hello @AhmedSalih3d , the “seed” paper for GPUSPH is [Hérault et al. (2010) SPH on GPU with CUDA](https://www.tandfonline.com/doi/abs/10.1080/00221686.2010.9641247). There is not a review paper discussing all new features of GPUSPH (yet), but for specific aspects there are other recommendations, feel free to ask. (BTW, you probably want to ask this kind of question on [the forum we've opened recently](https://gpusph.discourse.group/).

**Comment by AhmedSalih3d** [comment]
Thanks! I will be sure to use the forum next time for these types of questions.

Kind regards
