### ISSUE TITLE
DEM shift does not behave as it should

### ISSUE THREAD

**Issue by saltynexus** [GPUSPH/gpusph#61]
Applying a DEM shift, for example

`shift(dem,0.25,0,0);`

does not behave as one would assume. I’ve found that the DEM will virtually repeat itself over the domain, like graphic tiling. In other words, if the domain is 2 meters long, and the DEM is 0.5 meters long, there will be 4 adjacent copies of the DEM over the domain.

The “shift” function appears to act as a “window” or a " boxcar function" which starts at the shift location and then spans the width of the DEM. Only what lies in the “window” will be generated.

Continuing my example prior, if I define the shift at 0.25, then the "window" (width is 0.5m) will fill the domain with the last half of the DEM file (0.25-0.5), then see the next “tile” and fill the remainder of the domain with the first half of the DEM file (0-0.25). The window is staggered over copies 1 and 2, which is easily confirmed by changing the shift value.

In addition, there appears to be some kind of boundary around each copy which causes some loss of information in the tiling.

This is not how the shift should work. It should literally take the DEM and place it where you shifted it to. I don't know what's causing the weird behaviour because it is easy to get lost in the code for the DEM stuff. It could be either the DEM geometry or the way it is filled. I don't know.

**Comment by Oblomov** [comment]
I believe this is now fixed in `next`, please reopen if this is not the case.
