### ISSUE TITLE
Errors about running the examples

### ISSUE THREAD

**Issue by xuhenry** [GPUSPH/gpusph#62]
Hello, 
   I just compiled GPUSPH on my computer (Ubuntu 18.04). However, when I running the "make OpenChannel test"  There are the following errors:

FATAL: GPUSPH: problem during initialization
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
Makefile:1227: recipe for target 'test' failed
make: *** [test] Error 1

Thanks a lot!
Henry

**Comment by Oblomov** [comment]
Hello @xuhenry, GPUSPH should have given you an error before that FATAL. I'm guessing that what you are missing are the geometry files needed by OpenChannel. Can you try running `scripts/get_data_files`? This should fetch them.

**Comment by xuhenry** [comment]
Dear @Oblomov .Thanks a lot. There is something wrong about the MPI. It is ok now.
Thanks a lot!
Best regards,
Henry

**Comment by Oblomov** [comment]
Oh, good then. I'm closing the report.
