### ISSUE TITLE
Compile gpusph in nsight eclipse(cuda toolkit)

### ISSUE THREAD

**Issue by Dongxueyang** [GPUSPH/gpusph#66]
Hi everyone ,and @Oblomov @kgamiel @Narcolessico ,

We can compile the gpusph5.0 with makefile successfully. To modify the code and model file conveniently， Is it possible to compile the code in nsight eclipes(cuda toolkit), instead of using makefile. Because makefile is difficult to understand and modify, and nsight is a powerful tool with cudaGPU.
I have try to compile using nsight ,but I can not set the correct compile options. Often I get error about namespace cuneibs/cusph/cuphys/cuforces/cueuler. I change the include list but got other errors like undifined reference to "XXX" during nvlink.
"nvlink error : undefined reference to '_ZN5cusph17d_wcoeff_wendlandE' in ./src/problems/BuoyancyTest.o "

So is there someone who have compiled the code in nsight or been familiar to nsight compiling?
Thanks for help.
Dong

**Comment by Oblomov** [comment]
Hello @Dongxueyang 

we don't support building directly using an nsight/eclipse project, but you should still be able to import your project as a Makefile project and use the Create Make Target feature for each test case/target you want to build. Then building that make target should compile your test case. I just did a quick test by creating a DamBreak3D target from a freshly imported gpusph working directory and it seems to work.
