### ISSUE TITLE
About the makefile problem.

### ISSUE THREAD

**Issue by wnnies** [GPUSPH/gpusph#67]
Hello everyone,
@Oblomov :
I have go with the install file, but when I try to make test, it said “Makefile:53: Unable to determine GPUSPH version”. How should I deal with it?
Thank you!

**Comment by Oblomov** [comment]
Hello,

this is normal if you fetch a tarball instead of cloning from the git repository, you can safely ignore the message. (Although we should probably do something about this 8-P)

**Comment by wnnies** [comment]
Got it. Thank you so much!

**Comment by wnnies** [comment]
By the way, I tried to run the test case, but the simulation time always be 0 second. I changed the tend but didn't resolve this problem. Could you please tell me how to do? @Oblomov

**Comment by Oblomov** [comment]
You will need to provide more information about your hardware and software (operating system, CUDA and compiler versions, etc)

**Comment by wnnies** [comment]
cpu:AMD® Ryzen 5 2600
gpu: GeForce RTX 2060
os: Ubuntu 20.04.1 LTS
cuda: cuda_11.1.0_455.23.05_linux
complier: cmake

**Comment by Oblomov** [comment]
Can you try using the `next` branch and see if it solves the issue for you?

**Comment by Oblomov** [comment]
Given the absence of the reply, I'm assuming this issue was fixed in the `next` branch. Please reopen with additional information if this is not the case.
