### ISSUE TITLE
cannot open the .vtp file using paraview.

### ISSUE THREAD

**Issue by ZhenxiZhao** [GPUSPH/gpusph#74]
Dear all,
Recently, I encountered a problem which I never saw before.
I have created a topic in GPUSPH forum, please view the detail here.
https://gpusph.discourse.group/t/failed-when-open-the-vtp-file/160/7

And the testcase is attached below.
[cubewater.zip](https://github.com/GPUSPH/gpusph/files/7044958/cubewater.zip)

Best regards.

**Comment by ZhenxiZhao** [comment]
here comes the new information.

If I run testcase BuoyancyTest with m_deltap = 0.0022, which will generate 54,741,936 particles.
And the result are also unreadable (PART_00000).

It begins to be even more wired, when m_delta = 0.002(about 70 millions particles). everything is normal. Only when particles to be about 50 millions, this problem would emerge.

**Comment by ZhenxiZhao** [comment]
Have you reproduce the problem?
I didn't mean to border you. Just want to know that the problem is individual or common

**Comment by Oblomov** [comment]
This is fixed in next, commit 1bac5095e29429a8415e00cb0cca102bb62ef14d
