### ISSUE TITLE
Illegal memory access was encountered

### ISSUE THREAD

**Issue by Rixxuss** [GPUSPH/gpusph#75]
Hi,
When i run GPUSPH i get the following:

Entering the main simulation cycle
Simulation time t=0.000000e+00s, iteration=0, dt=2.925000e-04s, 84,444 parts (0, cum. 0 MIPPS), maxneibs 59+0
Device 0 thread 7f184160c000 iteration 0 last command: 43 (FORCES_SYNC). Exception: src/cuda/forces.cu(527) : in unbind_textures() @ thread 0x139742152802304 : cudaSafeCall() runtime API error 700 : an illegal memory access was encountered
GPUSPH aborted by worker thread
Elapsed time of simulation cycle: 0.036s
Peak particle speed was ~0 m/s at 0 s -> can set maximum vel 0 for this problem
Simulation end, cleaning up...
src/GPUWorker.cc(1106) : in deallocateDeviceBuffers() @ thread 0x139742152802304 : cudaSafeCall() runtime API error 700 : an illegal memory access was encountered
Deallocating...

Can you help me?
Kind regards

**Comment by Oblomov** [comment]
Hello,

could you please provide details about your setup, particularly:

1. GPUSPH version (or commit if using a git branch)
2. CUDA version
3. host compiler (g++ or clang) and version
4. CUDA GPU / architecture you're building for
5. does this happen with one of the shipped test case, and if so which one?

**Comment by Rixxuss** [comment]
Hi thanks for the reply.
1. main and v5.0
2. 11.1
3. gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
4. RTX 3090
5. I tried several of the test cases. One of them DamBreak3D.

**Comment by Oblomov** [comment]
There is a [known issue](https://github.com/NVIDIA/thrust/issues/1341) with Thrust from CUDA 11.1 that has been fixed in CUDA 11.3. The `next` branch of GPUSPH also contains a workaround for the issue, so it should work even with CUDA 11.1

Can you please verify if either of these upgrades fixes your issue?

**Comment by Rixxuss** [comment]
It does. Thank you.
