### ISSUE TITLE
I have too many errors about the cuh file , when i "make test" this source code.

### ISSUE THREAD

**Issue by hhan23** [GPUSPH/gpusph#76]
I have installed the chrono and used 12.0 CUDA with gtx1660ti, before i make test the code. The error message is as follows.
![image](https://user-images.githubusercontent.com/122416247/221884464-ab171385-6613-4fee-9452-758512df5378.png)
![image](https://user-images.githubusercontent.com/122416247/221884531-a852ae11-1c54-4e18-b5d9-a98d88c2a8f8.png)
![image](https://user-images.githubusercontent.com/122416247/221884586-1944a285-ee3e-41a8-92bb-8855c73cc64a.png)
![image](https://user-images.githubusercontent.com/122416247/221884660-cd772d25-cf44-437f-b3bc-8d3928316977.png)
![image](https://user-images.githubusercontent.com/122416247/221884713-1b09ba1c-2ff8-4fb4-8dc4-d7416667f35e.png)
![image](https://user-images.githubusercontent.com/122416247/221884821-c6f64c46-27ab-43bf-95d9-006005777cc5.png)
Hope you can help me solve this problem!
I'm looking forward to your reply .

**Comment by Oblomov** [comment]
Hello,

could you please specify which branch you're using and provide the output of `make show`?

**Comment by hhan23** [comment]
hello!
I just download the latest GPUSPH source code and following the gpusph-install.pdf. to  run make test to build the project.
I don't know which branch of the source I used.

**Comment by Oblomov** [comment]
The documentation on the website is a bit old. Can you please try the spheric2022 branch?

```
git clone git@github.com:GPUSPH/gpusph -b spheric2022
```

**Comment by hhan23** [comment]
Thank you! 
I have tried the 2022spheric branch. when i make the code , program tell me should download thrust . But i don't know which version of thrust i should download or where to define THRUST_IGNORE_CUB_VERSION_CHECK.
 
![image](https://user-images.githubusercontent.com/122416247/222093887-84873e3e-a5bf-40f0-bbb8-7a0ead7206eb.png)

**Comment by Oblomov** [comment]
Hello,

your CUDA installation should have come with Thrust installed. If it's not finding it, there might be some other issue with your setup.  If your distribution has thrust packaged (e.g. in Debian it's `libthrust-dev`) you should install that. Otherwise, try
```
./scripts/get-thrust
```
from the GPUSPH working directory.

You may also want to install `ascidoctor`, run `make docs` and look at the new installation guide that is under `docs/installation-guide.html`

**Comment by hhan23** [comment]
Thank you!

I have complied successfully. Could you please give me some suggestions to learn to build my own problems?

**Comment by Oblomov** [comment]
You can look at how other problems are set up by looking at the defaults shipped in `src/problems`. There is also a new user guide in `docs/` that you can build with AsciiDoctor, as mentioned above, that should generate a `docs/user-guide.html`. For further discussions on this topic, I would recommend using [our Discourse group](https://gpusph.discourse.group/).
