### ISSUE TITLE
An compile error: Texture is not a template

### ISSUE THREAD

**Issue by Haowei-Cai** [GPUSPH/gpusph#78]
Hello everyone,
When i using the GPUSPH5.0 to compile the given  problems, some errors called
```
src/cuda/textures.cuh(63): error: texture is not a template
  texture<float, 1, cudaReadModeElementType> posTex;
  ^
```
occur, the source file is src/cuda/textures.cuh(63 line to 89 line). I also try to compile in version 4.1, the same problems occur, with ```
src/cuda/bounds_kernel.cu(50): error: texture is not a template
  texture<float, 2, cudaReadModeElementType> demTex;
  ^
```
My system environment is below:
GPU: NVIDIA P3200 with max-Q
CUDA version: Cuda compilation tools, release 12.2, V12.2.91
                         Build cuda_12.2.r12.2/compiler.32965470_0
System: Ubuntu 22.04.2 LTS
GPUSPH version: v5.0 and v4.1

A problem puzzled me a lot, thank you very much for reply!

**Comment by Oblomov** [comment]
Hello @Haowei-Cai , can you try with the `spheric2022` branch?

**Comment by Haowei-Cai** [comment]
Thank you @Oblomov , Did you mean the problems named Spheric2LJ or Spheric2SA in <src>. After trying to make them, it is shown the same errors as before. Is this due to my cuda version ?

**Comment by Haowei-Cai** [comment]
@Oblomov Thank you sir, Spheric2022 does make sense! While how is the difference between the two branch and Why the formal main branch make some errors for my system ?

**Comment by Oblomov** [comment]
The `spheric2022` branch is a preview of v6 that was presented at the SPHERIC International Workshop last year. v6 has not been released yet because we're polishing some aspects still. I recommend using the `spheric2022` branch anyway. Since your issue is solved in the `spheric2022` branch,  I am closing this issue now.
