### ISSUE TITLE
OpenGL window

### ISSUE THREAD

**Issue by Ehsanizadi** [GPUSPH/gpusph#8]
Hi,
Is the run-time OpenGL window still available? If so, how to enbale it?
It was good stuff to visually debug the simulation.

Ehsan

**Comment by Narcolessico** [comment]
Hello,

Seewaves is a run-time viewer for GPUSPH simulations: http://people.renci.org/~kgamiel/seewaves/

About its usage: just add a `UDPWriter` in your problem and run Seewaves from the command line. It works also across a network - assuming the network is configured properly, of course ;)

Eugenio

**Comment by Ehsanizadi** [comment]
Thank you Eugenio
