### ISSUE TITLE
Error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Ehsanizadi** [GPUSPH/gpusph#9]
Hi all,

I am trying to model a box of mud (from StillWater example) and have a cylinder (rigid body from ODE) and let the the cylinder fall on the mud.

The code can be found here: https://github.com/Ehsanizadi/GPUSPH-Examples

when I run it with "./GPUSPH" command, i get the following log:
```
 * No devices specified, falling back to default (dev 0)...
GPUSPH version v3.0+50-c1c7ca3
Release version without fastmath for compute capability 3.5
Compiled for problem "Gprobe"
Hashkey is 64bits long
NetworkManager: no complete thread safety, current level: 2
[Network] rank 0 (1/1), host ehsan-UGent
 tot devs = 1 (1 * 1)
Initializing...
dt = 0.0001 (CFL conditions from soundspeed: 0.000975, from gravity 0.0273023, from viscosity 0.00660156)
Using problem-set max neibs num 3321 (safe computed value was 192)
Problem calling set grid params
Influence radius / expected cell side	: 0.1625, 0.19375
 - World origin: -0.5 , -0.5 , -0.5
 - World size:   1 x 1 x 1
 - Cell size:    0.2 x 0.2 x 0.2
 - Grid size:    5 x 5 x 5 (125 cells)
 - Cell linearizazion: x,z,y
 - Dp:   0.0625
 - R0:   0.0625
Generating problem particles...
Allocating shared host buffers...
  allocated 630.22 KiB on host for 5,041 particles
Copying the particles to shared arrays...
---
Boundary parts: 0
Boundary part mass: 0
Fluid parts: 1800
Fluid part mass: 0.472412
Vertex parts: 0
Vertex part mass: 0.472412
---
 - device at index 0 has 5,041 particles assigned and offset 0
Starting workers...
1 CUDA devices detected
Estimated memory consumption: 6880B/particle
number of rigid bodies particles = 3241
Device idx 0 (CUDA: 0) allocated 0 B on host, 33.16 MiB on device
  assigned particles: 5,041; allocated: 5,041
GPUSPH: initialized
Performing first write...
Letting threads upload the subdomains...
Thread 0 uploading 5041 Position items (78.77 KiB) on device 0 from position 0
Thread 0 uploading 5041 Velocity items (78.77 KiB) on device 0 from position 0
Thread 0 uploading 5041 Info items (39.38 KiB) on device 0 from position 0
Thread 0 uploading 5041 Hash items (39.38 KiB) on device 0 from position 0
Thread 0 uploading 5041 Boundary Elements items (78.77 KiB) on device 0 from position 0
Thread 0 uploading 5041 Gamma Gradient items (78.77 KiB) on device 0 from position 0
Thread 0 uploading 5041 Vertices items (78.77 KiB) on device 0 from position 0
Entering the main simulation cycle
Simulation time t=0.000000e+00s, iteration=0, dt=1.000000e-04s, 5,041 parts (0, cum. 0 MIPPS), maxneibs 3321
src/forces.cu(419) : cudaSafeCall() Runtime API error 77: an illegal memory access was encountered.
Deallocating...

```

Do you know what is the problem?

Thank you in advance for your help.
Ehsan

**Comment by Oblomov** [comment]
I think that the problem you are having is that you create the cylinder as a local variable in `fill_parts()`, so it gets destroyed at the end of the function. Try making the cylinder a member of the class instead.

**Comment by Ehsanizadi** [comment]
I tried to duplicate the pattern of defining objects like what exists in "OdeObjects" example (because I am totally newbie in GPUSPH!). So, why the objects in OdeObjects examples are not destroyed and the example runs well?

**Comment by Oblomov** [comment]
Because in `OdeObjects` the Sphere and Cylinder are declared as members of the class (see `OdeObjects.h`), and only initialized in `fill_parts()`; hence, the object persists as long as `OdeObjects` is instantiated (which is throughout the whole simulation). Instead, in your example you _declare_ the object in `fill_parts()`, so by C++ scoping rules it gets destroyed at the end of the function.

**Comment by Ehsanizadi** [comment]
I already declared the cylinder in the header file. However for being sure, even I declared the parameters for mass, radius, ect of cylinder in the header and assigned them in the class of the example in the cc file (not in the fill_parts() ).
However, I still get this error.

Maybe I am doing something like newbie mistake!?

**Comment by Oblomov** [comment]
If it's still segfaulting you'll have to compile the host code in debug mode (add a CXXFLAGS=-g to your Makefile.local, then run a make cpuclean and then make again) and use gdb to track the cause of segmentation fault.
